import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, SignUp } from "@clerk/nextjs";
import "./globals.css";
import Header from "../components/Header";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="en">
      <Head>
        <title>Medium – Where good ideas find you.</title>
        <meta name="description" content="Medium is an open platform where readers find dynamic thinking, and where expert and undiscovered voices can share their writing on any topic." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
